from __future__ import annotations

import json


_STUB_FUNCTIONS: dict[str, str] = {
    "search_notes": '''
def search_notes(query="", limit=None):
    """Search the Paper Notes library and return matching notes."""
    args = {"query": query}
    if limit is not None:
        args["limit"] = limit
    return _call("search_notes", args)
''',
    "get_note_context": '''
def get_note_context(note_id, query="", include_html=False, html_mode="body", max_paper_matches=4):
    """Build focused paper/note context for a Paper Notes note."""
    return _call("get_note_context", {
        "note_id": note_id,
        "query": query,
        "include_html": include_html,
        "html_mode": html_mode,
        "max_paper_matches": max_paper_matches,
    })
''',
    "read_paper": '''
def read_paper(
    action,
    note_id,
    query="",
    page=None,
    page_start=None,
    page_end=None,
    limit=None,
    max_chars=None,
    scale=None,
    artifact_id="",
    path="",
):
    """Read text, render pages, or inspect extracted paper content."""
    args = {"action": action, "note_id": note_id}
    optional = {
        "query": query,
        "page": page,
        "page_start": page_start,
        "page_end": page_end,
        "limit": limit,
        "max_chars": max_chars,
        "scale": scale,
        "artifact_id": artifact_id,
        "path": path,
    }
    args.update({key: value for key, value in optional.items() if value not in (None, "")})
    return _call("read_paper", args)
''',
    "review_note": '''
def review_note(action, note_id, heading="", html="", position="append"):
    """Preview or validate a Paper Notes HTML edit without writing it."""
    return _call("review_note", {
        "action": action,
        "note_id": note_id,
        "heading": heading,
        "html": html,
        "position": position,
    })
''',
    "session_search": '''
def session_search(query="", role_filter="", limit=5, include_recap=True):
    """Search or browse past Paper Notes chat sessions."""
    return _call("session_search", {
        "query": query,
        "role_filter": role_filter,
        "limit": limit,
        "include_recap": include_recap,
    })
''',
    "skills_list": '''
def skills_list(category=""):
    """List local agent skills with compact metadata."""
    args = {}
    if category:
        args["category"] = category
    return _call("skills_list", args)
''',
    "skill_view": '''
def skill_view(name, file_path=""):
    """Load a skill's instructions or a linked supporting file."""
    args = {"name": name}
    if file_path:
        args["file_path"] = file_path
    return _call("skill_view", args)
''',
    "web_search": '''
def web_search(query, limit=5, allowed_domains=None, recency_days=None, include_summary=True):
    """Search the configured custom web provider."""
    args = {
        "query": query,
        "limit": limit,
        "include_summary": include_summary,
    }
    if allowed_domains is not None:
        args["allowed_domains"] = allowed_domains
    if recency_days is not None:
        args["recency_days"] = recency_days
    return _call("web_search", args)
''',
    "web_fetch": '''
def web_fetch(url, max_chars=12000, include_links=False, format="markdown"):
    """Fetch readable text from a public URL."""
    return _call("web_fetch", {
        "url": url,
        "max_chars": max_chars,
        "include_links": include_links,
        "format": format,
    })
''',
}


def build_stub_source(enabled_tools: list[str] | tuple[str, ...] | set[str]) -> str:
    names = [str(name) for name in enabled_tools if str(name) in _STUB_FUNCTIONS]
    functions = "\n".join(_STUB_FUNCTIONS[name].strip() for name in names)
    all_names = ["_call", *names]
    return f'''# Generated by Paper Notes execute_code. Do not edit.
from __future__ import annotations

import json
import os
import socket


_RPC_HOST = os.environ.get("PAPER_NOTES_RPC_HOST", "127.0.0.1")
_RPC_PORT = int(os.environ.get("PAPER_NOTES_RPC_PORT", "0") or "0")
_RPC_TOKEN = os.environ.get("PAPER_NOTES_RPC_TOKEN", "")


def _call(tool_name, args=None):
    if not isinstance(args, dict):
        raise TypeError("tool args must be a dict")
    request = {{
        "token": _RPC_TOKEN,
        "tool": str(tool_name),
        "args": args,
    }}
    payload = (json.dumps(request, ensure_ascii=False) + "\\n").encode("utf-8")
    with socket.create_connection((_RPC_HOST, _RPC_PORT), timeout=30) as sock:
        sock.sendall(payload)
        chunks = []
        while True:
            chunk = sock.recv(65536)
            if not chunk:
                break
            chunks.append(chunk)
            if b"\\n" in chunk:
                break
    raw = b"".join(chunks).split(b"\\n", 1)[0]
    if not raw:
        return {{"success": False, "error": "Empty RPC response.", "code": "empty_rpc_response"}}
    return json.loads(raw.decode("utf-8", errors="replace"))


{functions}


__all__ = {json.dumps(all_names, ensure_ascii=False)}
'''


__all__ = ["build_stub_source"]
